### PR TITLE
Tweak package.json

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by brandonkelly** [comment]
Updating VP is more involved because we use a custom theme (https://github.com/pixelandtonic/vuepress-theme-craftdocs), and try to keep that up-to-date with changes to VuePress’s default theme.

**Comment by XhmikosR** [comment]
@brandonkelly: sure, I can just rebase the branch and drop the update patch only.

**Comment by brandonkelly** [comment]
Yeah that would be fine.

**Comment by XhmikosR** [comment]
@brandonkelly: done.

**Comment by brandonkelly** [comment]
Thanks!

**Pull request merged**
