### PR TITLE
Update set-password-form.md

### PR DESCRIPTION
**Pull request by billythekid**
fix for code and id not set in landing template

### CODE REVIEW

**Comment by brandonkelly** [comment]
Those variables should get passed to the template automatically.

**Comment by billythekid** [comment]
Yeah they should, and do if it’s the default setpassword form.

If you roll your own front end template they don’t appear to pass
through/get generated with routing.

**Comment by billythekid** [comment]
Ah, perhaps then I need to underscore my template and set the config to
that because having it as a path-accessible template doesn’t appear to set
the params.

Cheers Brandon, much obliged!

**Comment by j-greig** [comment]
> Are you trying to access the template directly? (You shouldn’t.) The template is rendered by the `users/set-password` controller action (which is what Set Password emails will link to), which always will pass those variables.

How do you include this template in a custom template?

**Comment by Anubarak** [comment]
@j-greig you should never include the template above in a custom template. It's exclusively for the purpose of changing the password when someone clicks on the generated link in a previously sended email. In order to change the password there is another form

**Comment by j-greig** [comment]
@Anubarak Thanks Robin! Where is the other form you mention?

**Comment by Anubarak** [comment]
Andrea already answered it perfectly at stack exchange herehttps://craftcms.stackexchange.com/a/28259/5557

You can use the normal user form https://docs.craftcms.com/v3/dev/examples/user-profile-form.html with the field `newPassword`

**Pull request closed without merging**
