### PR TITLE
save-user => saveUser

### PR DESCRIPTION
**Pull request by Totemika**
It does not work on my installation with "save-user" and it works with "saveUser", I haven't found any mention to kebab-case convention in Yii docs so I guess the correct one is `saveUser`...

### CODE REVIEW

**Comment by brandonkelly** [comment]
Guessing you’re working on a Craft 2 project? Yii 1 used `camelCase` URLs, but Yii 2 uses `kebab-case`.

**Comment by Totemika** [comment]
@brandonkelly it's a Craft 3 project, strange...

**Comment by Totemika** [comment]
Hi Brandon it's happening again; it fails at first with `updateCart` saying it's an invalid route; then I change it to 'update-cart' and it works. (yii2, Craft 3, Commerce 2) I removed `roave/security-advisories` just in case it was a version conflicting but does not solve it.
I can perfectly keep going using kebap-case until I find out where I am messing up but if you hear from this issue and it's solution please let me know.  Thanks

image

**Comment by brandonkelly** [comment]
Wait, this one is expected behavior right? https://github.com/craftcms/docs/blob/v3/en/changes-in-craft-3.md#action-params

**Comment by Totemika** [comment]
Yes, I got tremendously confused. Sorry 😞

**Comment by brandonkelly** [comment]
haha no worries :)

**Pull request closed without merging**
