### PR TITLE
Update general.md

### PR DESCRIPTION
**Pull request by leevigraham**
Fixed issue with `httpproxy` config docs

### CODE REVIEW

**Comment by AugustMiller** [comment]
Unfortunately, this portion of the docs is automatically generated from the Craft source code, so changes will be reverted during the next release.

I don't immediately see a solve for it over there, either—it seems like some Markdown is being parsed too early in the process, ignoring fenced code blocks.

I'll file an issue about this, to track a solution for something I fear is more widespread!

**Comment by leevigraham** [comment]
@AugustMiller Might be worth investigating a way to turn off "Edit this page" for content generated from source code.

**Comment by AugustMiller** [comment]
Aye, understood. Really, the auto-generated stuff should be entirely external to the `.md` files, and dynamically included by VuePress or a build step so that the _source_ is clear about what is/isn't manually editable.

Appreciate you kickstarting the conversation!

**Comment by leevigraham** [comment]
@AugustMiller It was actually raised on Discord :)

image

**Pull request closed without merging**
