### PR TITLE
pluginHandle casing

### PR DESCRIPTION
**Pull request by carlcs**

### CODE REVIEW

**Comment by takobell** [comment]
Technically neither way is right or wrong.  Yii will just look to the file system and try to match whatever category is passed into it: https://github.com/yiisoft/yii2/blob/master/framework/i18n/PhpMessageSource.php#L141

If you're on a case insensitive file system, it won't matter, but a case sensitive file system won't find the file.

Going to go ahead and leave it as lower case because 1) camelCase file names are weird and 2) it's consistent with lower cased plugin folder names, which are actually enforced.

**Comment by carlcs** [comment]
Ahh I see, thanks for the clarification @takobell. The term `pluginhandle` is confusing though, as it is set in the composer.json in camelCase and also used throughout the docs like so. Maybe rename to something like `plugincategory` or `myplugin`?

**Comment by carlcs** [comment]
Well, or leave it as is. I made the edit after reading through that docs section and thought is was a typo.

**Comment by takobell** [comment]
Yeah... we debated on this internally and this was the best of the worst choices we came up with.

**Comment by carlcs** [comment]
@takobell I just found this in the config file docs, which I think is a good solution

> Users will then be able to create a new file in their config/ folder named after your **plugin’s handle (lowercased)**, which returns an array that overrides whichever settings they want

**Comment by brandonkelly** [comment]
While the translation system doesn't care about category casing, plugins will by default get their own translation sources based on their exact plugin handle (without getting set to lowercase) – see [`craft\base\Plugin::init()`](https://github.com/craftcms/cms/blob/4499ca83629360682ff549e953388dd2f1d68c0f/src/base/Plugin.php#L56).

So will go ahead and make this change...

**Pull request closed without merging**
