### PR TITLE
Disable vuepress' prefetch.

### PR DESCRIPTION
**Pull request by XhmikosR**
We have many pages and this is just an overkill.

### CODE REVIEW

**Comment by brandonkelly** [comment]
What does this do exactly?

**Comment by XhmikosR** [comment]
If you open the generated HTML you will see it has tens of `link rel=prefetch`. So this starts having the opposite effect when there are too many prefetch links.

And example, see the waterfall https://gtmetrix.com/reports/docs.craftcms.com/YxUxfETl#waterfall or this one http://www.webpagetest.org/result/180807_GA_9ee394c882973ba43384b46805d44f00/

**Comment by brandonkelly** [comment]
Gotcha - yikes. I’ll do that for the v2 docs and class refereces as well.

**Comment by XhmikosR** [comment]
Definitely worth it.

**Pull request merged**
