### PR TITLE
Upgrading docs for customer info field

### PR DESCRIPTION
**Pull request by nfourtythree**
We had a migration that handled this previous, but it was causing issues with Project Config and also wasn't really the best way to handle it.

People will have to remove it manually now.

### CODE REVIEW

**Comment by nfourtythree** [comment]
Relevant: https://github.com/craftcms/commerce/commit/96858d299074d151963e9ef3ba21c58a97372463

**Comment by mattstein** [comment]
Sorry @nfourtythree I’m a little confused—you should definitely remove these fields by hand to avoid a project config bug, but also here’s how to make them show up?

Feels like we’re removing fields and explaining how to show them, but maybe we’re removing fields (as a mechanism) and we can display the same _information_ with the `showCustomerInfoTab` setting (which uses a template hook or different mechanism)?

**Comment by nfourtythree** [comment]
You won't get an error after that commit it released. But you will see the "field not found" message when viewing a user in the cp



Basically, all the information (and more new things) that was displayed in the customer info field is now covered by showing the customer info tab. Essentially it took its place as there wasn't really a need for it to be a field.

**Comment by mattstein** [comment]
Ah ... thank you! Critical part (I think): this only applies to me if I added that custom field to a layout at some point, right? (Or did Commerce add it automatically?)

**Comment by nfourtythree** [comment]
Yes, applies only if you had manually added it.

**Comment by mattstein** [comment]
I have no further questions. Thank you.

**Review by mattstein — APPROVED** [review]
I made an edit that’s still hopefully correct, but I’m technically the reviewer which makes me think I’m doing this wrong. Please object to any part of this you’d like—and if nobody says anything I’ll merge this when 3.3 drops.

**Comment by nfourtythree** [comment]
@mattstein Very happy with these changes. Because words.

This might sneak into a 3.2.x release so can be merged if/when that happens

**Comment by mattstein** [comment]
Good to know; currently folding everything into https://github.com/craftcms/docs/tree/next/commerce so I’ll _not_ delete this branch yet. :)

**Pull request merged**
