### PR TITLE
Add documentation on how to append files and preserve relations of assets

### PR DESCRIPTION
**Pull request by andreasottosson**
Add documentation on how to append files and preserve relations of assets.

### Description

We ran into this today, we wanted to have a front-end upload form and preserve existing relations to already uploaded files. This was not documented and Google didn't have much information about this use case. Hopefully this can helt someone trying to do the same thing.

### CODE REVIEW

**Comment by mattstein** [comment]
Thank you for this, @andreasottosson! Merging after a few edits I hope you don’t mind.

**Comment by andreasottosson** [comment]
@mattstein I don't mind at all, good to see this included in the docs! But I think the syntax highlighting is a bit weird right now on that section, it seems twig is only enabled for row 1-8, perhaps it is supposed to be like that. https://craftcms.com/docs/3.x/assets-fields.html#creating-new-assets

**Comment by mattstein** [comment]
@andreasottosson I highlighted the new chunk of Twig on purpose since it’s what the text just described, and the example re-includes redundant (but important) Twig shown earlier.

We use that highlight in a few places across the docs ([example](https://craftcms.com/docs/3.x/dev/twig-primer.html#loops))—are you saying the choice to emphasize that part feels weird in this context, or the visual highlight style is weird/uncomfortable in general?

**Comment by andreasottosson** [comment]
@mattstein Oh now I see what you did, yeah that's fine. I looked at it before my morning cup of coffee the first time ;)

**Comment by mattstein** [comment]
I understand, I try not to internet before coffee. Thanks again for the PR!

**Pull request merged**
