### PR TITLE
Reminder to run Setup Wizard after nitro create

### PR DESCRIPTION
**Pull request by Natetronn**
### Description

For those installing Craft directly, per the nitro docs, a reminder to run the Setup Wizard after `nitro create` has finished its job; this to complete the installation of Craft and write tables etc. to the database, otherwise they'll get error.

### Related issues
`HTTP 503 – Service Unavailable – craft\web\ServiceUnavailableHttpException.`

### CODE REVIEW

**Comment by mattstein** [comment]
Thanks @Natetronn! A `nitro create` project will run its Composer `post-create-project-cmd` commands, which [in Craft’s case](https://github.com/craftcms/craft/blob/4a69bfe7a49019a240d00dd0920697e33d08930d/composer.json#L41-L47) will include `@php craft setup/welcome` with a reminder to finish setup via `php craft setup`:

```
❯ nitro create test
Downloading https://github.com/craftcms/craft/archive/HEAD.zip ...
  … setting up project ✓
New site downloaded 🤓
Enter the hostname [test.nitro]:
  ✓ setting hostname to test.nitro
  ✓ adding site ~/test
Enter the web root for the site [web]:
  ✓ using web root web
Choose a PHP version:
  1. 8.0
  2. 7.4
  3. 7.3
  4. 7.2
  5. 7.1
  6. 7.0
Enter your selection: 1
  ✓ setting PHP version 8.0
Add a database for the site? [Y/n] Y
Select the database engine:
  1. mysql-8.0-3306.database.nitro
  2. postgres-13-5432.database.nitro
Enter your selection: 1
Enter the new database name: test
  … creating database test ✓
Database added 💪
Should we update the env file? [Y/n] Y
.env updated!
Preparing composer...

(skipping a lot of output)

> @php -r "file_exists('.env') || copy('.env.example', '.env');"
> @php -r "unlink('composer.json');"
> @php -r "rename('composer.json.default', 'composer.json');"
Generating optimized autoload files
Generated optimized autoload files containing 4291 classes
> @php craft setup/welcome

   ______ .______          ___       _______ .___________.
  /      ||   _  \        /   \     |   ____||           |
 |  ,----'|  |_)  |      /  ^  \    |  |__   `---|  |----`
 |  |     |      /      /  /_\  \   |   __|      |  |
 |  `----.|  |\  \----./  _____  \  |  |         |  |
  \______|| _| `._____/__/     \__\ |__|         |__|

     A       N   E   W       I   N   S   T   A   L   L
               ______ .___  ___.      _______.
              /      ||   \/   |     /       |
             |  ,----'|  \  /  |    |   (----`
             |  |     |  |\/|  |     \   \
             |  `----.|  |  |  | .----)   |
              \______||__|  |__| |_______/


Generating an application ID ... done (CraftCMS--d8eaf319-bc32-4245-88e6-87e95314aded)
Generating a security key ... done (M4FrX41tgm1JR7bMZRiNPY4g3j0IGwao)

Welcome to Craft CMS!

Run the following command if you want to setup Craft from your terminal:

    php /app/craft setup

composer command completed 🤘
```

It’s non-interactive and easy enough to miss, so I appreciate the note here.

And no argument about what number comes after `7`. 🤦‍♂️

**Comment by Natetronn** [comment]
Thanks @mattstein! 

I see the command you're referring to there and yes, I did miss it. I keep my terminal fairly small height wise; possibly another reason why I missed it, aside from it just running on by quickly, just in general. 

 If using nitro, I assume the command would be `nitro php /app/craft setup`, is that correct? 

Also, I guess it's not exactly clear why one would use that command, especially since I was under the impression that I was already setting up Craft from the terminal lol. Perhaps something to consider for Nitro V3.

Anyway, thanks again!

**Comment by mattstein** [comment]
>  If using nitro, I assume the command would be `nitro php /app/craft setup`, is that correct?

That would work, but the more straightforward command would be `nitro craft setup`, which I [just noted in that little tip](https://github.com/craftcms/docs/commit/5dacffa1a88e8a4c3049a0649d90fa8852b69119).

> Also, I guess it's not exactly clear why one would use that command, especially since I was under the impression that I was already setting up Craft from the terminal lol. Perhaps something to consider for Nitro V3.

IIRC Composer’s [create-project](https://getcomposer.org/doc/03-cli.md#create-project), which is used under the hood by `nitro create`, cannot be run interactively—so it can’t prompt you for the details the `craft setup` command needs. You _must_ run it yourself.

A new Craft instance has always involved two basic steps: environment and software setup so Craft _can_ run, then actually running Craft so it can install itself. `nitro create` takes care of the setup so you can more easily run the installer.

**Comment by Natetronn** [comment]
> A new Craft instance has always involved two basic steps: environment and software setup so Craft can run, then actually running Craft so it can install itself. nitro create takes care of the setup so you can more easily run the installer.

Fair enough. Thanks Matt!

**Pull request merged**
